// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXQfiVNEZqZxrf_kXfkFJuKSSb2qkgOQ',
    appId: '1:628039280861:web:a2bf9985d781219a8a1334',
    messagingSenderId: '628039280861',
    projectId: 'realtimedb-ac064',
    authDomain: 'realtimedb-ac064.firebaseapp.com',
    storageBucket: 'realtimedb-ac064.appspot.com',
    measurementId: 'G-DFNHQM0JPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHpNQaERKJV6Z4PV9lGCeMLRAqoPzboc',
    appId: '1:628039280861:android:7a37999bba2369f78a1334',
    messagingSenderId: '628039280861',
    projectId: 'realtimedb-ac064',
    storageBucket: 'realtimedb-ac064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_cM02KKZvMqUI57Xx63MWiIsuq-GRJwk',
    appId: '1:628039280861:ios:e3e932d13883f6318a1334',
    messagingSenderId: '628039280861',
    projectId: 'realtimedb-ac064',
    storageBucket: 'realtimedb-ac064.appspot.com',
    iosBundleId: 'com.example.rtDbUnivercityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_cM02KKZvMqUI57Xx63MWiIsuq-GRJwk',
    appId: '1:628039280861:ios:e3e932d13883f6318a1334',
    messagingSenderId: '628039280861',
    projectId: 'realtimedb-ac064',
    storageBucket: 'realtimedb-ac064.appspot.com',
    iosBundleId: 'com.example.rtDbUnivercityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQXQfiVNEZqZxrf_kXfkFJuKSSb2qkgOQ',
    appId: '1:628039280861:web:6c90e2760e4bfaf08a1334',
    messagingSenderId: '628039280861',
    projectId: 'realtimedb-ac064',
    authDomain: 'realtimedb-ac064.firebaseapp.com',
    storageBucket: 'realtimedb-ac064.appspot.com',
    measurementId: 'G-YHY9V86CGT',
  );
}
